# More about setting up Xdebug: https://docs.lando.dev/guides/lando-phpstorm.html#debugging-drush-commands
# More about setting up proxy addresses: https://docs.lando.dev/config/proxy.html
# More about installing the SSL certificate: https://docs.lando.dev/config/security.html#ubuntu-or-macos-with-firefox

# Require drupal/core-dev and phpspec/prophecy-phpunit as dev dependency in your composer.json and create a phpunit.xml
# file in the root of your project in order to use the test command

recipe: drupal9
template_version: '1.0.7'

config:
  php: '8.1'
  via: nginx
  webroot: web
  database: mariadb
  xdebug: false

proxy:
  appserver_nginx:
    - localhost
    - browsersync.localhost
    - simpletest.localhost
  mailhog:
    - mailhog.localhost
  phpmyadmin:
    - phpmyadmin.localhost

services:
  node:
    type: node:16
    overrides:
      ports:
        - "3000:3000"
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  cache:
    type: redis:4.0
    portforward: 6380
    persist: true
  appserver:
    xdebug: true
    build_as_root:
      - rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "localhost"
        PHP_IDE_CONFIG: "serverName=lando"
        SIMPLETEST_BASE_URL: "http://simpletest.localhost"
        SIMPLETEST_DB: "mysql://drupal9:drupal9@database/drupal9"
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://chrome:9515"]'

tooling:
  npx:
    service: node
  npm:
    service: node
  node:
    service: node
  redis-cli:
    service: cache
  test:
    service: appserver
    cmd: "php /app/vendor/bin/phpunit -c /app/phpunit.xml"
  drupalcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice"
    description: Run phpcs Drupal Coding Standards against a given file or directory.
  drupalcbf:
    service: appserver
    cmd: "/app/vendor/bin/phpcbf --standard=Drupal"
    description: Automatically fix Drupal coding standards suggestions.
  drupal-check:
    service: appserver
    cmd: "vendor/bin/drupal-check -ad"
    description: Check Drupal code for deprecations and discover bugs via static analysis.
  phpcbf:
    service: appserver
    cmd: "/app/vendor/bin/phpcbf --standard=PHPCompatibility --runtime-set testVersion 7.4 --extensions=php,module,inc,install,test,profile,theme,info"
    description: Automatically fix PHPCompatibility coding standards suggestions for PHP 7.4.
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion 7.4 --extensions=php,module,inc,install,test,profile,theme,info"
    description: Check code against the PHPCompatibility standard for PHP 7.4.
  dus:
    service: appserver
    cmd: "/usr/local/bin/composer outdated drupal/*"
    description: Displays the update status of your Drupal installation.
  dua:
    service: appserver
    cmd: "/usr/local/bin/composer outdated drupal/*; /usr/local/bin/composer update drupal/* -W; /app/vendor/drush/drush/drush cr; /app/vendor/drush/drush/drush updb; /app/vendor/drush/drush/drush cr; echo Do not forget to export configuration files!"
    description: Performs all available and allowed (according to composer.json) updates.
  duc:
    service: appserver
    cmd: "/usr/local/bin/composer outdated drupal/core 'drupal/core-*'; /usr/local/bin/composer update drupal/core 'drupal/core-*' -W; /app/vendor/drush/drush/drush cr; /app/vendor/drush/drush/drush updb; /app/vendor/drush/drush/drush cr; echo Do not forget to export configuration files!"
    description: Updates Drupal core only.
  duso:
    service: appserver
    cmd: "echo Composer based projects do not have the possibility to perform security updates only!"
    description: Only performs security updates for Drupal.
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm && echo "Xdebug enabled"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm && echo "Xdebug disabled"
    user: root
  sync:
    service: appserver
    level: app
    description: Sync database and files from server.
    cmd:
      - cd; curl -sO https://raw.githubusercontent.com/egoosmann/lando-drupal-template/master/sync-from-server.sh; chmod +x sync-from-server.sh; ./sync-from-server.sh; rm sync-from-server.sh;

events:
  pre-start:
    - cd; curl -sO https://raw.githubusercontent.com/egoosmann/lando-drupal-template/master/compare-template-version.sh; chmod +x compare-template-version.sh; ./compare-template-version.sh; rm compare-template-version.sh;
