# More about setting up Xdebug: https://docs.lando.dev/guides/lando-phpstorm.html#debugging-drush-commands
# More about setting up proxy addresses: https://docs.lando.dev/config/proxy.html
# More about installing the SSL certficate: https://docs.lando.dev/config/security.html#ubuntu-or-macos-with-firefox

# Require drupal/core-dev and phpspec/prophecy-phpunit as dev dependency in your composer.json and create a phpunit.xml
# file in the root of your project in order to use the test command

recipe: drupal7
template_version: '1.0.2'

config:
  php: '7.4'
  via: nginx
  database: mariadb
  xdebug: false

proxy:
  appserver_nginx:
    - localhost
    - browsersync.localhost
    - simpletest.localhost
  mailhog:
    - mailhog.localhost
  phpmyadmin:
    - phpmyadmin.localhost

services:
  node:
    type: node:14
    overrides:
      ports:
        - "3000:3000"
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  cache:
    type: redis:4.0
    portforward: 6380
    persist: true

tooling:
  npx:
    service: node
  npm:
    service: node
  node:
    service: node
  redis-cli:
    service: cache
  drupal-update-status:
    service: appserver
    cmd: "drush ups"
  drupal-update-all:
    service: appserver
    cmd: "drush up -y"
  drupal-update-core:
    service: appserver
    cmd: "drush up drupal -y"
  drupal-update-security-only:
    service: appserver
    cmd: "drush up --security-only -y"

events:
  pre-start:
    - cd; curl -sO https://raw.githubusercontent.com/egoosmann/lando-drupal-template/master/compare-template-version.sh; chmod +x compare-template-version.sh; ./compare-template-version.sh; rm compare-template-version.sh;
